- id: copyright
  name: check copyright year
  entry: copyright-check
  language: python
  types:
    - text
- id: copyright-required
  name: check copyright year
  entry: copyright-check
  args:
    - --required
  language: python
  types:
    - text
- id: workflows-require-timeout
  name: workflows require timeout
  description: Check that the workflows have a timeout
  entry: workflow-timeout-check
  files: ^\.github/workflows/.+\.ya?ml$
  language: python
- id: poetry-check
  name: poetry check
  description: Validates the structure of the pyproject.toml file
  entry: run-in-dir --cmd poetry check
  args:
    - --files
  language: python
  additional_dependencies:
    - poetry
  files: ^(|.*/)pyproject\.toml$
- id: poetry-lock
  name: poetry lock
  description: Lock the from the pyproject.toml file
  entry: run-in-dir --check poetry check --cmd poetry lock
  args:
    - -a--no-update
    - --files
  language: python
  additional_dependencies:
    - poetry
  files: ^(|.*/)pyproject\.toml$
- id: poetry2-lock
  name: poetry lock
  description: Lock the from the pyproject.toml file
  entry: run-in-dir --check poetry check --cmd poetry lock
  args:
    - --files
  language: python
  additional_dependencies:
    - poetry
  files: ^(|.*/)pyproject\.toml$
- id: pipenv-lock
  name: pipenv lock
  description: Lock the from the Pipfile file
  entry: run-in-dir --cmd pipenv lock
  args:
    - -a--keep-outdated
    - --files
  language: python
  additional_dependencies:
    - pipenv
  files: ^(|.*/)Pipfile$
- id: helm-lock
  name: helm lock
  description: Lock the from the Chart.yaml file
  entry: run-in-dir --cmd helm dependency update
  args:
    - --files
  language: python
  files: ^(|.*/)Chart\.yaml$
- id: npm-lock
  name: npm lock
  description: Lock the npm package from the package.json file
  entry: run-in-dir --cmd npm install
  args:
    - -a--package-lock-only
    - -a--ignore-scripts
    - --files
  language: python
  files: ^(|.*/)package\.json$
- id: canonicalize
  name: canonicalize files
  description: Canonicalize the files
  entry: sbrunner-canonicalize
  language: python
  files: |-
    (?x)^(
      \.github/workflows/[^/]+\.ya?ml
      |(|.*/)\.?prospector(-.*)?\.ya?ml
      |(|.*/)pyproject\.toml
      |(|.*/).pre-commit-config\.ya?ml
    )$
