- id: copyright
  name: check copyright year
  entry: pre-commit-copyright
  language: python
  types:
    - text
- id: copyright-required
  name: check copyright year
  entry: pre-commit-copyright
  args:
    - --required
  language: python
  types:
    - text
