strictness: veryhigh
max-line-length: 110
doc-warnings: True

pylint:
  disable:
    - too-many-arguments
    - too-many-statements
    - too-many-locals

pycodestyle:
  disable:
    - E501 # line too long
    - E203 # whitespace before ':'

bandit:
  run: true

mypy:
  run: true

pyroma:
  run: true

mccabe:
  run: false
