# Copyright (c) 2026, Stéphane Brunner

"""Compile the Python requirements from a `.in` file with `uv pip compile`."""

import argparse
import subprocess  # nosec
import sys
from pathlib import Path


def compiled_path(input_file: Path, extension: str) -> Path:
    """Get the path of the file generated from the input file."""
    return input_file.with_suffix(extension)


def build_command(
    input_file: Path,
    output_file: Path,
    python_version: str | None,
    hashes: bool,
    header: bool,
) -> list[str]:
    """
    Build the `uv pip compile` command.

    The hashes are generated by default to fully lock the dependencies, and the header is disabled
    by default because it contains the command line, which changes from one machine to another.
    The output is quiet because the hook is only expected to speak on failure.
    """
    command = ["uv", "pip", "compile", "--quiet"]
    if hashes:
        command.append("--generate-hashes")
    if not header:
        command.append("--no-header")
    if python_version is not None:
        command.append(f"--python-version={python_version}")
    command.append(f"--output-file={output_file}")
    command.append(f"{input_file}")
    return command


def run_compile(
    input_file: Path,
    output_file: Path,
    python_version: str | None,
    hashes: bool,
    header: bool,
) -> bool:
    """Compile the input file into the output file, in the input file folder."""
    command = build_command(input_file, output_file, python_version, hashes, header)
    print(f"Run '{' '.join(command)}' in '{input_file.parent}'")
    proc = subprocess.run(  # pylint: disable=subprocess-run-check # noqa: S603
        command,
        cwd=input_file.parent,
        check=False,
    )
    if proc.returncode != 0:
        print(f"Error: `uv pip compile` failed with the code {proc.returncode} on '{input_file}'")
        return False
    return True


def main() -> None:
    """Compile the Python requirements from a `.in` file with `uv pip compile`."""
    parser = argparse.ArgumentParser(
        description="""Compile the Python requirements from a `.in` file with `uv pip compile`.""",
    )
    parser.add_argument(
        "--python-version",
        help="The Python version used to resolve the dependencies, e.g.: 3.14",
    )
    parser.add_argument(
        "--extension",
        default=".txt",
        help="The extension of the generated file, `.txt` by default, it is a pip requirements file",
    )
    parser.add_argument(
        "--no-hashes",
        action="store_true",
        help="Do not pass `--generate-hashes` to `uv pip compile`",
    )
    parser.add_argument(
        "--header",
        action="store_true",
        help="Do not pass `--no-header` to `uv pip compile`",
    )
    parser.add_argument("files", nargs=argparse.REMAINDER, help="The `.in` files to compile")
    args = parser.parse_args()

    success = True
    for input_file in [Path(filename) for filename in args.files]:
        if input_file.suffix != ".in":
            print(f"Ignore '{input_file}', not a `.in` file")
            continue
        success = (
            run_compile(
                input_file,
                compiled_path(input_file, args.extension),
                args.python_version,
                not args.no_hashes,
                args.header,
            )
            and success
        )

    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
